name: Package

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Create the package
        run: dotnet pack --configuration Debug --no-build --no-restore --version-suffix $GITVERSION_SEMVER -o .

      - name: Publish the package
        run: dotnet nuget push -s https://nuget.nwcloudsolutions.com/v3/index.json -k ${{ secrets.NUGET_API_KEY }} *.nupkg          